name: Despliegue de Frontend Estático a GitHub Pages

on:
  push:
    branches:
      # La rama de origen del código para el despliegue Temporalmente aqui pero luego main
      - dev 
  
  # Permite ejecutar el flujo manualmente si es necesario
  workflow_dispatch:

jobs:
  deploy: # Nombre del job simplificado
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del Código
        # Obtiene el código de la rama 'dev'
        uses: actions/checkout@v4
      
      - name: Despliegue a GitHub Pages
        # Acción para manejar la lógica de Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token de GitHub para permitir la publicación
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # ¡IMPORTANTE! Indica que la carpeta a publicar es 'frontend'
          publish_dir: ./frontend 
          
          # La rama de destino que GitHub Pages leerá
          publish_branch: gh-pages
